name: Deploy NotesTracker.Database

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # Build the database project to generate the .dacpac file
    - name: Build Database Project
      run:  |
        dotnet build NotesTracker.Database/NotesTracker.Database.sqlproj --configuration Release

    # Deploy the .dacpac file to Azure SQL Database
    - name: Deploy to Azure SQL Database
      uses: azure/sql-action@v2
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: NotesTracker.Database/bin/Release/NotesTracker.Database.dacpac
