name: Build and Deploy NotesTracker

env:
    API_PROJECT_PATH: NotesTracker.API/NotesTracker.API.csproj
    WEB_PROJECT_PATH: NotesTracker.Web
    DATABASE_PROJECT_PATH: NotesTracker.Database/NotesTracker.Database.sqlproj
    FUNCTION_PROJECT_PATH:

on:
    workflow_dispatch:
        inputs:
            deploy_api:
                description: "NotesTracker.API"
                required: false
                default: false
                type: boolean

            deploy_function:
                description: "NotesTracker.Function"
                required: false
                default: false
                type: boolean

            deploy_web:
                description: "NotesTracker.Web"
                required: false
                default: false
                type: boolean

            deploy_database:
                description: "NotesTracker.Database"
                required: false
                default: false
                type: boolean

jobs:
    # region BUILD AND DEPLOY API

    build-and-deploy-api:
        name: "Build and Deploy NotesTracker.API"
        if: ${{ inputs.deploy_api }}
        runs-on: ubuntu-latest
        environment: Laboratory

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up .NET
            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            # Install dependencies and build the project
            - name: Install dependencies and build Solution
              run: |
                  dotnet restore ${{ env.API_PROJECT_PATH }}
                  dotnet build ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore

            # Publish the project to a folder
            - name: Publish the project
              run: |
                  dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --output ./publish

            # Deploy to Azure App Service
            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: app-webapi-notes-tracker
                  slot-name: production
                  publish-profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}
                  package: ./publish

    #endregion

    # region BUILD AND DEPLOY FUNCTIONS

    build-and-deploy-function:
        name: "Build and Deploy NotesTracker.Functions"
        if: ${{ inputs.deploy_function }}
        runs-on: ubuntu-latest
        environment: Laboratory

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up .NET
            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            # Install dependencies and build Azure Function project
            - name: Install dependencies and build Function
              run: |
                  dotnet restore ${{ env.FUNCTION_PROJECT_PATH }}
                  dotnet build ${{ env.FUNCTION_PROJECT_PATH }} --configuration Release --no-restore

            # Publish the Azure Functions project to a folder
            - name: Publish the Function project
              run: |
                  dotnet publish ${{ env.FUNCTION_PROJECT_PATH }} --configuration Release --output ./publish-functions

            # Run Azure Functions action
            - name: Run Azure Functions action
              uses: Azure/functions-action@v1
              with:
                  app-name: func-notes-tracker
                  package: ./publish-functions
                  sku: "flexconsumption"
                  publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}

    #endregion

    # region BUILD AND DEPLOY WEB

    build-and-deploy-web:
        name: "Build and Deploy NotesTracker.Web"
        if: ${{ inputs.deploy_web }}
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            # Install dependencies and build the Angular project
            - name: Install dependencies and build Web
              run: |
                  cd ${{ env.WEB_PROJECT_PATH }}
                  npm install
                  npm run build

            # Deploy the Angular project to Azure App Service
            - name: Deploy Web to Azure Web App
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_HILL_03D2EF300 }}
                  action: "upload"
                  app_location: ${{ env.WEB_PROJECT_PATH }}
                  output_location: "dist/notes-tracker-web/browser"

    #endregion

    # region BUILD AND DEPLOY DATABASE

    build-and-deploy-database:
        name: "Build and Deploy NotesTracker.Database"
        if: ${{ inputs.deploy_database }}
        runs-on: windows-latest
        environment: Laboratory

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Azure Login
            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_DB_SECRET }}

            # Setup .NET
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            # Install dependencies
            - name: Install dependencies and build solution
              run: |
                  dotnet restore ${{ env.DATABASE_PROJECT_PATH }}
                  dotnet build ${{ env.DATABASE_PROJECT_PATH }} --configuration Release --no-restore

            # Publish the dacpac to a folder
            - name: Publish the dacpac file
              run: |
                  dotnet publish ${{ env.DATABASE_PROJECT_PATH }} --configuration Release --output ./publish-db

            # Deploy to Azure SQL Server
            - name: Deploy to Azure SQL Server
              uses: azure/sql-action@v2.3
              with:
                  connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
                  path: "./publish-db/NotesTracker.Database.dacpac"
                  action: "publish"
                  arguments: "/p:DropObjectsNotInSource=true"

    #endregion
