name: CI-CD for NotesTracker

on:
  push:
    branches:
      - main 
      - dev

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Use the .NET version specified in your project

    # Install dependencies and build the project
    - name: Install dependencies and build
      run: |
        dotnet restore NotesTracker.API/NotesTracker.API.csproj
        dotnet build NotesTracker.API/NotesTracker.API.csproj --configuration Release --no-restore

    # Publish the project to a folder
    - name: Publish the project
      run: |
        dotnet publish NotesTracker.API/NotesTracker.API.csproj --configuration Release --output ./publish

    # Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-webapi-notes-tracker # Replace with your Azure App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish