name: Build and Deploy NotesTracker

on:
  workflow_dispatch:
    inputs:
      deploy_api:
        description: 'Build and Deploy NotesTracker.API'
        required: false
        default: true
        type: boolean

      deploy_function:
        description: 'Build and Deploy NotesTracker.Function'
        required: false
        default: true
        type: boolean

      deploy_web:
        description: 'Build and Deploy NotesTracker.Web'
        required: false
        default: true
        type: boolean

      deploy_database:
        description: 'Build and Deploy NotesTracker.Database'
        required: false
        default: true
        type: boolean

jobs:
  # STEP: BUILD AND DEPLOY API
  build-and-deploy-api:
    name: 'Build and Deploy NotesTracker.API'
    if: ${{ inputs.deploy_api }}
    uses: './.github/workflows/deploy-api.yml'

  # STEP: BUILD AND DEPLOY FUNCTIONS
  build-and-deploy-function:
    name: 'Build and Deploy NotesTracker.Functions'
    if: ${{ inputs.deploy_function }}
    uses: './.github/workflows/deploy-functions.yml'

  # STEP: BUILD AND DEPLOY WEB
  build-and-deploy-web:
    name: 'Build and Deploy NotesTracker.Web'
    if: ${{ inputs.deploy_web }}
    uses: './.github/workflows/deploy-web.yml'

  # STEP: BUILD AND DEPLOY DATABASE
  build-and-deploy-database:
    name: 'Build and Deploy NotesTracker.Database'
    if: ${{ inputs.deploy_database }}
    uses: './.github/workflows/deploy-database.yml'