name: Build and Deploy NotesTracker

on:
  workflow_dispatch:
    inputs:
      deploy_api:
        description: 'Build and Deploy NotesTracker.API'
        required: false
        default: false
        type: boolean

      deploy_function:
        description: 'Build and Deploy NotesTracker.Function'
        required: false
        default: false
        type: boolean

      deploy_web:
        description: 'Build and Deploy NotesTracker.Web'
        required: false
        default: false
        type: boolean

      deploy_database:
        description: 'Build and Deploy NotesTracker.Database'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  # STEP: BUILD AND DEPLOY API
  build-and-deploy-api:
    name: 'Build and Deploy NotesTracker.API'
    if: ${{ inputs.deploy_api }}
    uses: './.github/workflows/deploy-api.yml'
    with:
      azure_managed_identity_client_id: ${{ secrets.AZURE_MANAGED_IDENTITY_CLIENT_ID }}
      azure_credentials_tenant_id: ${{ secrets.AZURE_CREDENTIALS_TENANT_ID }}
      azure_credentials_subscription_id: ${{ secrets.AZURE_CREDENTIALS_SUBSCRIPTION_ID }}
      azure_webapi_publish_profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}

  # STEP: BUILD AND DEPLOY FUNCTIONS
  build-and-deploy-function:
    name: 'Build and Deploy NotesTracker.Functions'
    if: ${{ inputs.deploy_function }}
    uses: './.github/workflows/deploy-functions.yml'

  # STEP: BUILD AND DEPLOY WEB
  build-and-deploy-web:
    name: 'Build and Deploy NotesTracker.Web'
    if: ${{ inputs.deploy_web }}
    uses: './.github/workflows/deploy-web.yml'

  # STEP: BUILD AND DEPLOY DATABASE
  build-and-deploy-database:
    name: 'Build and Deploy NotesTracker.Database'
    if: ${{ inputs.deploy_database }}
    uses: './.github/workflows/deploy-database.yml'