name: Build and Deploy NotesTracker.API

on:
  workflow_call:
    
jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug
      run:  |
        echo CLID: ${{ secrets.AZURE_MANAGED_IDENTITY_CLIENT_ID }}
        echo TNID: ${{ secrets.AZURE_CREDENTIALS_TENANT_ID }}
        echo SBID: ${{ secrets.AZURE_CREDENTIALS_SUBSCRIPTION_ID }}

    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        auth-type: IDENTITY
        client-id: ${{ secrets.AZURE_MANAGED_IDENTITY_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_CREDENTIALS_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_CREDENTIALS_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
        allow-no-subscriptions: true

    # Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # Install dependencies and build the project
    - name: Install dependencies and build Solution
      run: |
        dotnet restore NotesTracker.API/NotesTracker.API.csproj
        dotnet build NotesTracker.API/NotesTracker.API.csproj --configuration Release --no-restore

    # Publish the project to a folder
    - name: Publish the project
      run: |
        dotnet publish NotesTracker.API/NotesTracker.API.csproj --configuration Release --output ./publish

    # Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-webapi-notes-tracker
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}
        package: ./publish

        