name: Build and Deploy NotesTracker.Web

on:
  workflow_call:

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Install dependencies and build the Angular project
    - name: Install dependencies and build Web
      run: |
        cd NotesTracker.Web
        npm install
        npm run build

    # Deploy the Angular project to Azure App Service
    - name: Deploy Web to Azure Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: 'upload'
        app_location: 'NotesTracker.Web'
        output_location: 'dist/notes-tracker-web/browser'