name: CI-CD for NotesTracker

on:
  workflow_dispatch:
    inputs:
      deploy_api:
        description: 'Deploy NotesTracker.API'
        required: false
        default: false
        type: boolean

      deploy_function:
        description: 'Deploy NotesTracker.Function'
        required: false
        default: false
        type: boolean

      deploy_web:
        description: 'Deploy NotesTracker.Web'
        required: false
        default: false
        type: boolean

      deploy_database:
        description: 'Deploy NotesTracker.Database'
        required: false
        default: false
        type: boolean

jobs:
  build-and-deploy-api:
    name: 'Build and Deploy NotesTracker.API'
    if: ${{ inputs.deploy_api == 'true' }}
    uses: ./.github/workflows/templates/deploy-api.yml
    

  build-and-deploy-function:
    name: 'Build and Deploy NotesTracker.Functions'
    if: ${{ inputs.deploy_function == 'true' }}
    uses: ./.github/workflows/templates/deploy-function.yml

  build-and-deploy-web:
    name: 'Build and Deploy NotesTracker.Web'
    if: ${{ inputs.deploy_web == 'true' }}
    uses: './.github/workflows/templates/deploy-web.yml'

  build-and-deploy-database:
    name: 'Build and Deploy NotesTracker.Database'
    if: ${{ inputs.deploy_database == 'true' }}
    uses: './.github/workflows/templates/deploy-database.yml'
    