name: Build and Deploy NotesTracker.API

on:
  workflow_call:
    inputs:
      azure_managed_identity_client_id:
        required: true
        type: string
      azure_credentials_tenant_id:
        required: true
        type: string
      azure_credentials_subscription_id:
        required: true
        type: string
      azure_webapi_publish_profile:
        required: true
        type: string

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug
      run:  |
        echo CLID: ${{ inputs.azure_managed_identity_client_id }}
        echo TNID: ${{ inputs.azure_credentials_tenant_id }}
        echo SBID: ${{ inputs.azure_credentials_subscription_id }}

    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        auth-type: IDENTITY
        client-id: ${{ inputs.azure_managed_identity_client_id }}
        tenant-id: ${{ inputs.azure_credentials_tenant_id }}
        subscription-id: ${{ inputs.azure_credentials_subscription_id }}
        enable-AzPSSession: true
        allow-no-subscriptions: true

    # Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # Install dependencies and build the project
    - name: Install dependencies and build Solution
      run: |
        dotnet restore NotesTracker.API/NotesTracker.API.csproj
        dotnet build NotesTracker.API/NotesTracker.API.csproj --configuration Release --no-restore

    # Publish the project to a folder
    - name: Publish the project
      run: |
        dotnet publish NotesTracker.API/NotesTracker.API.csproj --configuration Release --output ./publish

    # Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-webapi-notes-tracker
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}
        package: ./publish

        